# Generated by Django 3.2.19 on 2023-06-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_auto_20230610_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opcionais',
            new_name='Opcional',
        ),
    ]
