# Generated by Django 3.2.19 on 2023-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_rename_opcionais_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='fotos_moto'),
        ),
    ]
