# Generated by Django 3.2.19 on 2023-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0004_moto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='foto',
        ),
        migrations.AddField(
            model_name='moto',
            name='foto_1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='moto',
            name='foto_2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='moto',
            name='foto_3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='moto',
            name='foto_4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='moto',
            name='foto_principal',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
